version: "2.3"

services:
  # search_engine:
  #   image: reid
  #   container_name: data_server
  #   ports:
  #     - 6669:6669
  detector:
    image: per_det
    container_name: person_detector
    runtime: nvidia
    ports:
      - 6666:6666
  feature:
    image: fea_ext
    container_name: feature_extraxtor
    runtime: nvidia
    ports:
      - 6667:6667
  person_attribute:
    image: par2
    container_name: par
    runtime: nvidia
    ports:
      - 6669:6669
  action:
    image: act
    container_name: action_recognition
    runtime: nvidia
    ports:
      - 6671:6671
